blank_issues_enabled: false
contact_links:
  - name: Elastic Community Support
    url: https://discuss.elastic.co
    about: Please ask and answer questions here.
  - name: Elastic Security
    url: https://www.elastic.co/community/security
    about: Please report security vulnerabilities here.
